_target_: src.datasets.NonlinearStringDataset
fs: 96000
dur: 3
method_name: "sav"
num_modes: 75
gamma_range: [174.62, 246.94]
kappa_range: [1.05, 1.1]
mu_range: [123.48, 174.62]
sigma0_range: [2, 2]
sigma1_range: [2e-4, 2e-4]
xe_range: [0.1, 0.9]
xo_range: [0.1, 0.9]
exc_amp_range: [3.5e4, 5e4]
exc_dur_range: [0.5e-3, 1.5e-3]
exc_type: 1
nl_name: "spectral"
num_variations: 60
seed: 0
float_dtype: "double"
method_kwargs: {lambda0: 1e3}
nl_kwargs: {use_exact: True, use_linear: False}